name: Release

on:
  push:
    tags: [ 'v*.*.**' ]
    branches:
      - master
      - master/**
      - main
      - main/**
      - develop
      - v*
      - release/**



jobs:
  tag-snapshot:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    uses:  "hboyd2003/github-ci/.github/workflows/tag-snapshot.yml@master"
    permissions:
      contents: "write"
    secrets: "inherit"
  release:
    uses:  "hboyd2003/github-ci/.github/workflows/java-release.yml@master"
    permissions:
      contents: "write"
    with:
      tag_name: "${{ startsWith(github.ref, 'refs/tags/v') && github.ref || 'snapshot' }}"
    secrets: "inherit"